import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import './globals.css'

import logoImg from '@/assets/logo.svg'
import clsx from 'clsx'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ignite Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={clsx('bg-gray-900 text-white antialiased', inter.className)}
      >
        <header className="mx-auto w-full max-w-6xl py-10">
          <Link href={'/'}>
            <Image
              src={logoImg}
              width={130}
              height={52}
              alt="Logo do Ignite Shop"
            />
          </Link>
        </header>
        {children}
      </body>
    </html>
  )
}
